name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - run: mv list.html index.html
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@master
      env:
        secrets: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: .
